// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf7g26tTW-7Pt5lWUUbHxhV4vTDoCF6_s',
    appId: '1:704258118725:android:758cdb4e87a9396a247f2c',
    messagingSenderId: '704258118725',
    projectId: 'capstone-project-bbafe',
    databaseURL: 'https://capstone-project-bbafe-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'capstone-project-bbafe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpTB3TkHUHd42PhV3w4fsLJWdBHAbeEGk',
    appId: '1:704258118725:ios:9dac7f0524152f9a247f2c',
    messagingSenderId: '704258118725',
    projectId: 'capstone-project-bbafe',
    databaseURL: 'https://capstone-project-bbafe-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'capstone-project-bbafe.appspot.com',
    iosBundleId: 'com.rplacino.usersApp',
  );
}
